workflows:
  ios-workflow:
    name: iOS Workflow
    integrations:
      app_store_connect: Codemagic
    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.fixer.kpre
    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Inject provisioning profile
        script: |
          xcode-project use-profiles
          echo "--- pbxproj check ---"
          grep "PROVISIONING_PROFILE_SPECIFIER" ios/Runner.xcodeproj/project.pbxproj

      - name: Flutter build IPA
        script: |
          flutter build ipa --release --export-method app-store

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration