// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_twkW5-a2TXEJyxSjs7CSgbruWDtd5nA',
    appId: '1:172882778974:web:915a5c400ddb6c68abcdcf',
    messagingSenderId: '172882778974',
    projectId: 'fixco-dc493-8d57c',
    authDomain: 'fixco-dc493-8d57c.firebaseapp.com',
    storageBucket: 'fixco-dc493-8d57c.firebasestorage.app',
    measurementId: 'G-WCBE6DB644',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbsBk-n7vBwQhS9eLEySgC2VUOYMUvwJc',
    appId: '1:172882778974:android:09153a1d5fcb7689abcdcf',
    messagingSenderId: '172882778974',
    projectId: 'fixco-dc493-8d57c',
    storageBucket: 'fixco-dc493-8d57c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNxh8URazNOYwFEXW0oatwu0tzLk28crU',
    appId: '1:172882778974:ios:29ebc4ab572e44ffabcdcf',
    messagingSenderId: '172882778974',
    projectId: 'fixco-dc493-8d57c',
    storageBucket: 'fixco-dc493-8d57c.firebasestorage.app',
    iosBundleId: 'com.example.fixco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNxh8URazNOYwFEXW0oatwu0tzLk28crU',
    appId: '1:172882778974:ios:29ebc4ab572e44ffabcdcf',
    messagingSenderId: '172882778974',
    projectId: 'fixco-dc493-8d57c',
    storageBucket: 'fixco-dc493-8d57c.firebasestorage.app',
    iosBundleId: 'com.example.fixco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_twkW5-a2TXEJyxSjs7CSgbruWDtd5nA',
    appId: '1:172882778974:web:ae7ac49bde9ae40babcdcf',
    messagingSenderId: '172882778974',
    projectId: 'fixco-dc493-8d57c',
    authDomain: 'fixco-dc493-8d57c.firebaseapp.com',
    storageBucket: 'fixco-dc493-8d57c.firebasestorage.app',
    measurementId: 'G-SD8ESC5MMT',
  );
}
